### PR TITLE
Reactify the views

### LINKED ISSUE #373: Reactify all the views
@shivamsinghchahar _a

### PR DESCRIPTION
**Pull request by shivamsinghchahar**
Fixes #373

### CODE REVIEW

**Comment by vinay0x** [comment]
@shivamsinghchahar Let's get this merged after the tests pass. There are some restructures that we need to do with the React part. I'll take care of it. Since we need this ASAP, back and forth might take some time. After I make the changes, I'll let you know so that you can also take a look.

**Comment by vinay0x** [comment]
@neerajdotname Can we merge this PR into `develop` branch so that I can add my changes into that branch before merging it to master? I'm only asking since Wheel is public.

**Comment by shivamsinghchahar** [comment]
@vinay0x Sure, I'll fix the tests

**Comment by neerajdotname** [comment]
@vinay0x sure. And we don't need to change anything just because it is public. Let's follow the style the way we work.

**Comment by vinay0x** [comment]
@shivamsinghchahar I've changed the target branch to `develop`. Please merge it when it looks good.

**Pull request merged**
