### PR TITLE
Removed codeowners file

### PR DESCRIPTION
**Pull request by anmol-kumar0815**

### CODE REVIEW

**Comment by yedhink** [comment]
@anmol-kumar0815 As far as I can comprehend, it's very clearly written in the basecamp doc regarding to which repo PRs ought to be made.

Lemme know if the following is not very clear to you.

image

**Comment by anmol-kumar0815** [comment]
Yedhin: I am sorry for the mistake. I will keep this in mind and will not repeat this. Actually I am not very much familiar with github, and due to default settings I accidentally made this mistake. But now I know the settings I will not make this mistake again.

**Comment by yedhink** [comment]
@anmol-kumar0815 If you need any sort of help regarding `git` or `github`, then please make sure to ask in the ch2022 channel. It's better to learn it the right way by clarifying your queries.

**Comment by neerajdotname** [comment]
>due to default settings

@anmol-kumar0815 Could you please elaborate on what you mean by "due to default settings".

**Comment by anmol-kumar0815** [comment]
Neeraj: After doing fork from `https://github.com/bigbinary/wheel.git` when I opened my repository i.e  `https://github.com/anmol-kumar0815/wheel` and read README file, It was mentioned there Clone this repo by running git clone `https://github.com/bigbinary/wheel.git`. As I mentioned I was not very much familiar with `git` and `github`, I was not aware that I have to clone it from `https://github.com/anmol-kumar0815/wheel` not from `https://github.com/bigbinary/wheel.git`, this was the first mistake that I made and because of this my git remote origin url was set to bigbinary/wheel repository and when I pushed new branch to the GitHub (using git push origin branch_name) and created pull request, the base repository was set to bigbinary/wheel by default(At that time I was not aware that I had to change this) I clicked on create pull request button and this is how I made this mistake.

Screenshot 2022-09-18 at 1 13 20 AM

**Comment by neerajdotname** [comment]
@yedhink To avoid such issues I think the README of [wheel](https://github.com/bigbinary/wheel) should be changed from

```
Clone this repo by running git clone https://github.com/bigbinary/wheel.git.
```

to 

```
Clone this repo.
```

Some of these folks are using Git/Github for the first time. So I think this is fair.

**Comment by yedhink** [comment]
Done.

**Pull request closed without merging**
