### PR TITLE
Testing running rubocop for only changed files in semaphore

### PR DESCRIPTION
**Pull request by yedhink**
Please don't merge. Only for testing purposes.

### CODE REVIEW

**Comment by yedhink** [comment]
@neerajdotname @unnitallman 

Please go through the video and let me know your thoughts.

https://youtu.be/0JDmwU2lj0M

**Comment by neerajdotname** [comment]
@yedhink @Vishal24367 //cc @unnitallman https://www.loom.com/share/575311efdfee465bac6be1439ecf436c

**Comment by neerajdotname** [comment]
I thought this was related to AceInvoice somehow.

**Comment by unnitallman** [comment]
@yedhink @neerajdotname 

1. I think that we should run rubocop on all the files in the CI.
2. It is safe to  run `rubocop -a` and send a single PR for that. if the test suite passes and with something manual tests, we can safely merge it. I don't foresee any issues coming out of this.
3. If only a small number of issues (5 as @yedhink says) remain, which needs to be fixed manually, I think its worth creating an issue and getting it fixed and then letting Rubocop run on all files everytime in the CI.

The work around (with a temp file) that Yedhin suggested is indeed hacky and not reliable. We may be able to find out better and reliable ways to make Rubocop run only on changed files - but I think we should just fix all the errors and then let Rubocop run on all the files.

**Comment by neerajdotname** [comment]
@unnitallman sounds good.

**Pull request closed without merging**
