### PR TITLE
Corrected browserlistrc and updated node version

### LINKED ISSUE #957: Update node version to 18.12
1. Update node version to 18.12 similar to other neeto products. This is necessary to make the corresponding changes in neetoIcons, neetoUI, and neetoEditor packages.
2. Update the `.browserslist` file to be similar to https://github.com/bigbinary/neeto-desk-web/blob/main/.browserslistrc. Both neetoUI and neetoEditor has some feature that won't be supported in some older browsers.

@yedhink _a can you please assign one person to work on this issue?

### PR DESCRIPTION
**Pull request by navaneethsdk**
Fixes #957

### CODE REVIEW

**Comment by yedhink** [comment]
@navaneethsdk _a Please fix the CI.

**Comment by unnitallman** [comment]
bug _t

**Comment by navaneethsdk** [comment]
>  Could we get this merged/closed as is relevant?
@unnitallman Unfortunately not. I had integrated `shakapacker` after seeking guidance from @ferbin17. Although the assets were compiled without any errors, the UI broke. I was later drawn to some high-priority work and had to put this on hold. I will take this up with high priority if it's relevant.

**Comment by yedhink** [comment]
Unni: Right now Navaneeth is assigned with some high priority work. If this PR needs to be closed, then we can do that and later open it once again.

**Comment by unnitallman** [comment]
@yedhink Not urgent. Just wanted to add it to his plate so that he can pick up when he gets some time.

**Comment by yedhink** [comment]
@jagannathBhat _a Can you please check why neetoCI is failing for this PR? Is it because the script is trying to fetch the git remote in neetoCI and the neetoCI codebase itself, rather than wheel, is fetched or something?

image

**Comment by jagannathBhat** [comment]
@yedhink I have solved the issue with the eslint script. It was simply missing the `babel-plugin-dynamic-import-node` package.

There are some rails test failures please take a look @navaneethsdk _a

**Comment by yedhink** [comment]
@yedhink _A

**Pull request merged**
