### PR TITLE
Upgraded ruby to 3.0.3

### PR DESCRIPTION
**Pull request by chiraggshah**

### CODE REVIEW

**Comment by chiraggshah** [comment]
@yedhink _a : Please review

**Comment by ghousemohamed** [comment]
@yedhink we currently do not have an image for 3.0.3

Let me create an image for that version and make a corresponding commit here.

**Comment by ghousemohamed** [comment]
@yedhink I've added the Docker image for ruby 3.0.3 in dockerhub. This can be merged now if it looks good.

**Comment by ghousemohamed** [comment]
@yedhink _a

**Comment by yedhink** [comment]
@unnitallman The Ruby version has been updated to 3.0.3. Letting you know about this so that if anything needs to be updated in compliance, then it can be done.

cc: @prasanthchaduvula

**Pull request merged**
