### PR TITLE
Removed unused styles

### LINKED ISSUE #495: Remove unwanted stylesheet
Screenshot 2021-05-14 at 1 46 35 PM

@goutham-subramanyam _a

cc: @vinay0x

### PR DESCRIPTION
**Pull request by goutham-subramanyam**
Fixes #495 

@vinay0x _a

### CODE REVIEW

**Comment by vinay0x** [comment]
@goutham-subramanyam _a There's a deployment failure. Can you please check?

**Comment by vinay0x** [comment]
@goutham-subramanyam _a Some styles seem to be broken.
image
Also, toastr's styling is toasted 😜 
image

**Comment by goutham-subramanyam** [comment]
@vinay0x _a I have fixed the issues. Please check.

**Comment by vinay0x** [comment]
Looks good!

**Pull request merged**
