### PR TITLE
[WIP] Upgrade to Rails 5.1.0.beta1

### PR DESCRIPTION
**Pull request by bknarendra**

### CODE REVIEW

**Comment by bknarendra** [comment]
@neerajdotname I debugged into deprecation warnings and found issues in gems we used. I have raised the issue with gems where it wasn’t raised or found already raised issues with some gems. Following are the issues for deprecations found.
* Issue with the carrierwave using now deprecated method changes instead of new method saved_changes. Found this issue that someone has raised already https://github.com/carrierwaveuploader/carrierwave/issues/2115. Tried fixing the issue however there is some issue with fix and tests are breaking. Need to debug more.

* Haml gem uses ActionView::Template::Handlers::Erubis instead of ActionView::Template::Handlers::ERB::Erubi. Although haml fixed the issue in it latest 5.0.0 beta. However haml-rails still uses old haml version. So raised an issue with haml-rails https://github.com/indirect/haml-rails/issues/121

**Comment by neerajdotname** [comment]
@bknarendra other than warnings is everything else working ok ?

**Comment by mohitnatoo** [comment]
I see above that the app failed to deploy on heroku. I am however unable to view this app by using credentials of `bot@bigbinary.com`. 

I am facing similar heroku deployment related issues during assets precompile stage while upgrading in timely. I was hoping to see the build logs here if the error is same.

FYI this is the error I am looking to resolve currently in timely.
https://monosnap.com/file/nSD2FhaFKkjDNzQu9hPS0c96ubKSgS

**Comment by neerajdotname** [comment]
@mohitnatoo If you login with bot@bigbinary.com in heroku then you should be able to see it now.

**Comment by neerajdotname** [comment]
In Gemfile we have `gem 'fog-aws', require: false`. Notice require is false. That could be one reason.

**Comment by neerajdotname** [comment]
On a different note `rake db:migrate` failed for me.

```
nsingh ~/code/bigbinary-projects/wheel 153_rails_upgrade_to_5_1_0_beta
$ rdbm
DEPRECATION WARNING: ActionView::Template::Handlers::Erubis is deprecated and will be removed from Rails 5.2. Switch to ActionView::Template::Handlers::ERB::Erubi instead. (called from <top (required)> at /Users/nsingh/code/bigbinary-projects/wheel/config/application.rb:8)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class AddDeviseToUsers < ActiveRecord::Migration[4.2]
/Users/nsingh/code/bigbinary-projects/wheel/db/migrate/20131112184628_add_devise_to_users.rb:1:in `<top (required)>'
/Users/nsingh/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/nsingh/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class AddDeviseToUsers < ActiveRecord::Migration[4.2]
/Users/nsingh/code/bigbinary-projects/wheel/db/migrate/20131112184628_add_devise_to_users.rb:1:in `<top (required)>'
/Users/nsingh/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/nsingh/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```

**Comment by mohitnatoo** [comment]
Also, instead of `ActiveRecord::Migration[4.2]`, I think we should make all migrations to `ActiveRecord::Migration[5.1]`. 

Because wheel is an app from which most of our apps will be built, hence let us have migrations to latest version.

**Comment by neerajdotname** [comment]
@mohitnatoo I agree.

**Comment by bknarendra** [comment]
@neerajdotname @mohitnatoo Although I will update the migrations to use versioning. However, the migration didn't break for me. How were you able to produce it.

**Comment by bknarendra** [comment]
@neerajdotname @mohitnatoo please review

**Pull request merged**
