### PR TITLE
Added logic to handle secrets with care

### LINKED ISSUE #787: Research on ways to handle env variables for production env in secrets.yml
@yedhink _a

### PR DESCRIPTION
**Pull request by yedhink**
Fixes #787 

@unnitallman _a

Please review.

- We handle common secrets in a `common` variable
- This variable can be queried by neetoCompliance and made sure to comply
- All OR hardcoded values have been moved to `.env.development`.

Lemme know your thoughts on this and if there is a scope for improvement. Thanks

### CODE REVIEW

**Review by unnitallman — APPROVED** [review]

**Comment by yedhink** [comment]
@unnitallman I am a bit confused about https://github.com/bigbinary/wheel/pull/793#discussion_r811092318 given that you had marked it as resolved. 

Do we need to make that change or can we merge this? Lemme know your thoughts.

**Review by unnitallman — COMMENTED** [review]
Would like to have a call regarding this @yedhink

**Comment by yedhink** [comment]
@unnitallman _a Have removed the comment. Please review.

**Review by unnitallman — APPROVED** [review]

**Comment by yedhink** [comment]
Closing as we have already adopted a pattern across neeto.

**Pull request closed without merging**
