### PR TITLE
Updated libraries

### LINKED ISSUE #316: Update libraries
Screen Shot 2020-06-01 at 2 54 08 PM

### PR DESCRIPTION
**Pull request by ashiksp**
Fixes #316

### CODE REVIEW

**Comment by ashiksp** [comment]
Failure: https://circleci.com/gh/bigbinary/wheel/1786

**Comment by ashiksp** [comment]
Success: https://circleci.com/gh/bigbinary/wheel/1787

@neerajdotname  Please review the changes.

**Comment by neerajdotname** [comment]
@ashiksp I do not see any change in `package.json`. What command you executed to update just `yarn.lock` without making any changes to `package.json` ?

**Comment by ashiksp** [comment]
@neerajdotname  I have updated the libraries.

Removed `node_modules` & `yarn.lock` and run `yarn install`.

**Pull request merged**
