### PR TITLE
Reformed Formik validations

### LINKED ISSUE #941: Reform form validation standards.
Part of https://github.com/bigbinary/bigbinary-website/issues/2670

### PR DESCRIPTION
**Pull request by navaneethsdk**
Fixes #941

### CODE REVIEW

**Comment by navaneethsdk** [comment]
@yedhink _a

**Comment by yedhink** [comment]
@navaneethsdk _a Please put up a demo of how the fields show error validations now. Also please look into what's causing the CI to fail.

**Comment by navaneethsdk** [comment]
@yedhin _a. Please see this video:
https://www.loom.com/share/87e7081c8e8248ba8dfb2a7c9662c34f

**Comment by navaneethsdk** [comment]
Screenshot 2023-01-17 at 10 27 42 AM
Yedhin the CI failed during the audit check and I am guessing it is not because of the UI changes. It asks to upgrade the ruby version.

**Comment by neerajdotname** [comment]
@navaneethsdk Rest of the neeto products are on `3.1.3`. So let's upgrade this also to `3.1.31.

https://github.com/bigbinary/neeto-chat-web/blob/main/.ruby-version

**Comment by navaneethsdk** [comment]
> @navaneethsdk Rest of the neeto products are on `3.1.3`. So let's upgrade this also to `3.1.31.
> 
> https://github.com/bigbinary/neeto-chat-web/blob/main/.ruby-version

Thanks Neeraj. I will take this up.

**Comment by yedhink** [comment]
@navaneethsdk I have raised a separate issue for it https://github.com/bigbinary/wheel/issues/943. Let's fix it first and then rebase this branch later.

**Comment by yedhink** [comment]
@navaneethsdk _a Once the other issue is fixed, please rebase and assign this back to me.

**Comment by navaneethsdk** [comment]
@yedhink _a. Kindly review and merge.

**Pull request merged**
