### PR TITLE
Updated storage helper methods

### LINKED ISSUE #719: Improve way of managing null values in storage.js
## setToLocalStorage

https://github.com/bigbinary/wheel/blob/ecfddd6aa16d2ae9ec78df160a4f0786f397de6d/app/javascript/src/helpers/storage.js#L1-L3
Should be replaced with:
```js
const setToLocalStorage = (key, value) => {
  if (value != null) {
    localStorage.setItem(key, JSON.stringify(value));
  } else localStorage.removeItem(key);
};
```
Reason: null values need not be saved. The key should be removed in such case.

## getFromLocalStorage

https://github.com/bigbinary/wheel/blob/ecfddd6aa16d2ae9ec78df160a4f0786f397de6d/app/javascript/src/helpers/storage.js#L5-L14
Should be replaced with:
```js
const getFromLocalStorage = key => JSON.parse(localStorage.getItem(key));
```
Reason: When the above change is made, this one-liner will perform the same way as the old one.
Edge cases: when no item exists in localStorage with given key, `localStorage.getItem(key)` retrieves `null`. `JSON.parse(null)` returns `null`

### PR DESCRIPTION
**Pull request by rishabhanand12**
Fixes #719 

@rishabhanand12 _a

### CODE REVIEW

**Comment by rishabhanand12** [comment]
@yedhink _a Please take a look.

**Comment by yedhink** [comment]
@rishabhanand12 _a

Can you please double verify from UI that this change doesn't affect:
- Login
- Signup
- Logout
- Login and then closing browser and reopening page plus refreshing it

This helper might be used in neeto products too. Thus we need to double verify before merging.

**Comment by rishabhanand12** [comment]
@yedhink I have verified the features as suggested. I have a question. Please take a look https://www.loom.com/share/9d8f7c353d7947d8aed6a0cc972573d8. 

P.S. One thing I forgot to mention in the video is that the behaviour is same in master branch.

**Comment by yedhink** [comment]
@rishabhanand12 _a

This is the issue that lead to use adding that `isLoggedIn` logic in the first place: https://github.com/bigbinary/wheel/issues/680#issue-1028339676

I guess, if user is not logged in, then we should clear the localStorage tokens say in PrivateRoute itself.

> We should use sessions

Why do you think we need to use sessions in this case?

**Comment by rishabhanand12** [comment]
@yedhink We could clear the local state in `PrivateRoute` but that doesn't fix the issue. User should be logged in if the browser is force closed, right?

I suggested to use session storage because I was under the impression that logging the user out after session ends is an intentional feature. In that case it made more sense to use session storage.

**Comment by yedhink** [comment]
Tracking this issue in https://github.com/bigbinary/wheel/issues/774

Putting this PR on hold until we fix that issue.

**Comment by yedhink** [comment]
The issue with browser quit has been fixed.

We use simple auth token based strategy and we persist these tokens in localStorage. But the session of the user is handled via session-cookies, by Devise.

So I think we can add a logic in client side, that checks for presence of `props.user` from backend. There are few cases we need to handle:
- localStorage doesn't have any data - then we don't have to do anything - the current code is good enough
- localStorage has authToken etc but the session has expired - but props.user is NOT present - in this specific case, we should clear the localStorage

@rishabhanand12 _a

Please take this up. Lemme know if you have any queries.

**Comment by rishabhanand12** [comment]
@yedhink _a I have verified that the application is working as intended after #774 fix and I have also checked for cases mentioned in https://github.com/bigbinary/wheel/pull/765#issuecomment-1019878181.

I don't think we need to add any additional logic to clear the localstorage if the session data from devise is null. Please take a look.

**Pull request merged**
