### PR TITLE
Fixed failing login spec

### PR DESCRIPTION
**Pull request by Prasannams97**
Fixes: #806

### CODE REVIEW

**Comment by Prasannams97** [comment]
@Prasannams97 _a

**Comment by Prasannams97** [comment]
cypress _t

**Comment by Prasannams97** [comment]
@prabhakarbattula _a Please review.

**Comment by prabhakarbattula** [comment]
@Prasannams97 _a LGTM.

**Comment by Prasannams97** [comment]
@yedhink _a Merge this PR.

**Pull request merged**
