### PR TITLE
 Added reference of type file

### PR DESCRIPTION
**Pull request by Harshit-frontend**
Ref: https://github.com/bigbinary/neeto-commons-frontend/issues/215

### CODE REVIEW

**Comment by yedhink** [comment]
@Harshit-frontend Can you please point out why exactly this change is needed? Asking because there is issue linked nor no description in the first comment of this PR.

**Comment by yedhink** [comment]
@Harshit-frontend Please point out where exactly, in this PR or in wheel `master` branch this file called `types.d.ts` is present. I checked this PR till commit `5da5715fa31058cb83d05a13fcd7d97180c7cd14`(final commit) and couldn't find such a file. 

Thanks.

**Comment by Harshit-frontend** [comment]
> @Harshit-frontend Please point out where exactly, in this PR or in wheel `master` branch this file called `types.d.ts` is present. I checked this PR till commit `5da5715fa31058cb83d05a13fcd7d97180c7cd14`(final commit) and couldn't find such a file.
> 
> Thanks.

@yedhink Currently It is not present. It will be available via neetoCompliance under `app/src/javascript`

**Comment by yedhink** [comment]
@Harshit-frontend There are few things that I want you to do here:

- I want you to carefully look into the name of this repo.
- If you feel this is the exact repo where this PR ought to be made, then please point out why this repo ought to be neeto compliant.
- If you strongly feel this repo ought to be neeto compliant, then I want you to go through the Gemfile of this repo and point out whether neetoCompliance related gems have been already added or not to substantiate your previous comment, which was: `It will be available via neetoCompliance`.
- Last and most importantly, I want you to carefully read: https://handbook.neetokb.com/articles/git-and-github-essentials#self-review-process

Some other side notes:
- The title of the PR doesn't convey what exactly is being done in this PR. It's very vague. A better title would have been `Added TypeScript declaration file with general types and referenced it in App.jsx`
- The branch name doesn't follow the proper naming conventions. Refer: https://handbook.neetokb.com/articles/git-and-github-essentials#creating-a-branch

**Comment by Harshit-frontend** [comment]
Thanks for the explanation. I will delete this PR

**Pull request closed without merging**
