### PR TITLE
Enable turbo link

### PR DESCRIPTION
**Pull request by kalamkar**
- [x] in code
- [x] updated README

@kalamkar _a

### CODE REVIEW

**Comment by kalamkar** [comment]
@neerajdotname _a Please review

**Comment by neerajdotname** [comment]
@kalamkar _a Please keep javascript tag in the footer.

**Comment by kalamkar** [comment]
@neerajdotname 

Turbolinks automatically fetches the page, swaps in its `<body>`, and merges its `<head>`

When we put `javascript_include_tag` in the footer, it reloads JavaScript files for every `<body>` swap and try to redefine already defined JavaScript modules.

As Turbolinks makes navigating web application faster, IMO it would not affect the performance when `javascript_include_tag` is in the `<head>`. 

Please let me know your views.

**Comment by neerajdotname** [comment]
@kalamkar Good point. I had forgotten that now we have enabled turbo link.

**Pull request merged**
