### PR TITLE
Trigger cypress tests

### PR DESCRIPTION
**Pull request by Prasannams97**
Fixes: #735

### CODE REVIEW

**Comment by Prasannams97** [comment]
cypress _t mergepr _t

**Comment by Prasannams97** [comment]
@yedhink _a Can you please approve this PR, need to check the `mergepr` label workflow.

**Review by yedhink — APPROVED** [review]

**Comment by Prasannams97** [comment]
@unnitallman _a `mergepr` label is not working here, can you please check.

**Comment by unnitallman** [comment]
cypress _t mergepr _t

**Comment by yedhink** [comment]
@unnitallman Is this PR stale? If yes, can we close this? Thanks.

**Pull request closed without merging**
