### PR TITLE
Added tailwind

### PR DESCRIPTION
**Pull request by rishimohan**
Fixes https://github.com/bigbinary/wheel/issues/336

### CODE REVIEW

**Comment by rishimohan** [comment]
@vinay0x _a I've followed couple of tutorials on this but tailwind classes aren't working for some reason, not sure what I'm missing here, can you please help and assign it back to me, thanks.

**Comment by vinay0x** [comment]
@rishimohan I'll get back to you on this by EOD.

**Comment by vinay0x** [comment]
@rishimohan _a I've pushed a commit that fixes Tailwind. I've also made a change to `app/views/shared/header/_nav_links.html.slim` to demonstrate that it's working. Please remove `bg-red-500` from line 7 after you verify that it's working. 

All I did was move the Tailwind imports to the default `application.scss` file and import it.

**Comment by rishimohan** [comment]
@vinay0x _a

https://www.loom.com/share/d980ab90c0194936a3744da9fce0fd46

**Comment by vinay0x** [comment]
@rishimohan _a I missed a commit 😄 Sorry about that. Can you check now?

**Comment by vinay0x** [comment]
@rishimohan https://wheel-pr-338.herokuapp.com/ Looks like it's working now

**Comment by rishimohan** [comment]
@vinay0x Thanks, didn't know we need to declare it in postcss.yml file too.

**Comment by rishimohan** [comment]
@neerajdotname _a Please review, also please share access to Heroku so I can fix the deployment, thanks.

https://www.loom.com/share/9aa038ce97e64e5599c792b80599fb6c

**Comment by neerajdotname** [comment]
@srijan-kapoor _a can you fix the minitest issue.

**Comment by neerajdotname** [comment]
@rishimohan looks good. 

- [ ] change "create account" to "signup" to be consistent
- [ ] Remove the 2019 message from the footer. Yes remove it rather than fixing it.

**Comment by srijan-kapoor** [comment]
This branch is missing the `semaphore.yml` file which is causing the CI to fail. Could you rebase the PR @rishimohan?

**Comment by rishimohan** [comment]
@srijan-kapoor _a Can you please help with minitest.

**Comment by srijan-kapoor** [comment]
Have we removed the display of inline errors with tailwind?  @rishimohan 

The test case is failing when looking up for the `has_error` CSS class which was getting added in case of bootstrap as seen here. This class doesn't get added when using tailwind.

**With bootstrap**

Screenshot 2020-08-12 at 12 46 25 AM

Screenshot 2020-08-12 at 1 17 34 AM

Test assertion which performs this check
https://github.com/bigbinary/wheel/blob/master/test/controllers/registrations_controller_test.rb#L54

**Comment by rishimohan** [comment]
@neerajdotname _a Tests are passing, please review - https://wheel-pr-338.herokuapp.com/

**Pull request merged**
