### PR TITLE
Dockerize wheel app with docker compose

### PR DESCRIPTION
**Pull request by RahulMahale**

### CODE REVIEW

**Comment by RahulMahale** [comment]
@vipulnsward _a

**Comment by neerajdotname** [comment]
@vipulnsward can you take a look at this. READEME needs to be updated.

**Comment by neerajdotname** [comment]
@RahulMahale pl add Running with Docker to readme toc.

**Comment by RahulMahale** [comment]
@neerajdotname we have instructions in readme https://github.com/bigbinary/wheel#running-with-docker

**Comment by neerajdotname** [comment]
@RahulMahale at the top of readme there is toc. it should be there also.

**Comment by vipulnsward** [comment]
@neerajdotname It has been fixed https://github.com/bigbinary/wheel#toc

**Comment by neerajdotname** [comment]
Excellent.

**Pull request merged**
