### PR TITLE
Upgraded `neetoUI` to `v3.2.13`

### LINKED ISSUE #759: Upgrade to neetoUI v3
@rishabhanand12 _a

cc: @yedhink @karthiknmenon

### PR DESCRIPTION
**Pull request by rishabhanand12**
Fixes #759 

@yedhink _a Please take a look.

### CODE REVIEW

**Comment by yedhink** [comment]
@rishabhanand12 _a

The asset pre-compilation is failing.

Please go through neetoUI docs for installation part.

If you need further reference check https://github.com/bigbinary/neeto-chat-web/pull/2040/files

You can verify whether compilation is working locally by following https://www.bigbinary.com/learn-rubyonrails-book/webpacker-in-depth#webpacker-during-deployment

**Comment by yedhink** [comment]
@rishabhanand12 _a

What's the delay with this PR? Please work on this high priority. PRs in wheel should be merged as soon as possible.

**Comment by rishabhanand12** [comment]
@yedhink I ran the following command to see why asset pre-compilation is failing
```
SECRET_KEY_BASE=`cat config/master.key.sample` RAILS_ENV=production RAILS_SERVE_STATIC_FILES=off bundle exec rails assets:precompile
```

Apparently SCSS files are not found during the pre compilation. I am working on this. Could you also give me access to Heroku logs.

**Comment by yedhink** [comment]
@rishabhanand12 Seems to me that you don't have an account in Heroku with your `rishabh.anand@bigbinary.com` email. Please create an account and then let me know.

**Comment by rishabhanand12** [comment]
@yedhink _a I have fixed the failing asset pre-compilation. `tailwindcss` could not be loaded during production so I moved it to `dependencies`. Please take a look.

**Comment by yedhink** [comment]
@rishabhanand12 _a

https://www.loom.com/share/bda60981e4ec42e3b1fc024feae71518

**Comment by rishabhanand12** [comment]
@yedhink _a I have compared and tested the changes. Please take a look.

**Comment by yedhink** [comment]
@rishabhanand12 _a

We don't need a `current password` in `My Profile`:
image

Also, make sure profile updates as well as password change is working as expected.

**Comment by rishabhanand12** [comment]
@yedhink I believe the current password field is present to validate the request. I will remove it. 
Profile update is not working because we don't have an API for it. I was working on adding it and I have a question. We have a `users_controller` and a `registration_controller`. 

Registration basically means signup, right? The business logic for signup is present in the `users_controller`. In `registrations_controller` we have an `update_password` action which handles password updates. Do we need the `registrations_controller`?

**Comment by rishabhanand12** [comment]
Also the changes that you have mentioned would be more suitable for https://github.com/bigbinary/wheel/pull/761. Since we have updated the profile component in that PR. Can I make the change in that PR?

**Comment by yedhink** [comment]
@rishabhanand12 https://www.loom.com/share/6d1f264284d54a52865c412ed58abaad

**Pull request merged**
